name: Problem
description: Create an issue related to a device changing functionality after adapter update
labels: [device function change]
body:
    - type: markdown
      attributes:
          value: |
              **IMPORTANT:** Before submitting:             
              - check whether the issue is linked to a single device or a group of devices
              - obtain device specific debug logs for this device from at least 2 different adapter versions - one where the device operated as known (previous) and one where the device operates now (current)
              - Device specific debug is activated by clicking the bug button on the back of the device card.
              - do **not** use this issue template to request support for new devices.
              **Note that issues which do not include the requested debug logs will not be addressed**
              **Note 2: Issues with log messages without proper code tags will not be addressed. Proper code tags are being generated by first pasting the log into the text field, marking it and then selecting the 'code' button for the editor**.
    - type: textarea
      id: what_problem
      attributes:
          label: describe the changes between the device operation problem in Detail. What is the curernt state, what is the desired state ?
      validations:
          required: true    
    - type: input
      id: device_info
      attributes:
          label: Device information (Type of the device, **including** the Z2M link to the device description page)
          description: The information and link to the device are available in the info display accessible from the backside of the device card
          placeholder: 'WSDCGQ11LM https://www.zigbee2mqtt.io/devices/WSDCGQ11LM.html'
      validations:
          required: true
    - type: input
      id: coordinator_fwversion
      attributes:
          label: Coordinator firmware version
          description: Can be found in the Adapter settings
          placeholder: '20230921'
      validations:
          required: true
    - type: input
      id: coordinator_type
      attributes:
          label: Coordinator 
          description: Hardware Coordinator
          placeholder: Electrolama zig-a-zig-ah! (zzh!), Slaeshs CC2652RB stick, SONOFF Zigbee 3.0 USB Dongle Plus ...
      validations:
          required: true                    
    - type: input
      id: setup
      attributes:
          label: Setup
          description: How do you run the adapter 
          placeholder: Add-on on Intel NUC, Docker container, RaspberryPi...
      validations:
          required: true        
    - type: input
      id: adapter_version 
      attributes:
          label: Current adapter version
          description: Can be found in the Admin GUI
          placeholder: '3.1.2'
      validations:
          required: true          
    - type: textarea
      id: log
      attributes:
          label: Protocol of the error (as text, encapsulated in multiline code tags <>). Logs which are too big to be shown in the issue **must** be trimmed so that they fit, e.g. by removing duplicate warning messages.
          description: ELEVATED warning messages for the device from the ioBroker protocol. Note - Include any error messages encountered with the warnings, but no info or debug messages
          placeholder: Paste the log in here.
      validations:
          required: true
    - type: input
      id: adapter_version2
      attributes:
          label: Previous adapter version
          description: Can be found in the Admin GUI
          placeholder: '1.10.3'
      validations:
          required: true          
    - type: textarea
      id: log2
      attributes:
          label: Protocol of the error (as text, encapsulated in multiline code tags <>). Logs which are too big to be shown in the issue **must** be trimmed so that they fit, e.g. by removing duplicate warning messages.
          description: ELEVATED warning messages for the device from the obroker protocol. NOTE - Include any error messages encountered with the warnings, but no info or debug messages
          placeholder: Paste the log in here.
      validations:
          required: true
          
